env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
ignorePatterns:
  ["*.test.js", "src/serviceWorkerRegistration.ts", "service-worker.ts"]
rules:
  {
    "arrow-body-style": 0,
    "react/jsx-uses-react": 0,
    "react/react-in-jsx-scope": 0,
    "react/function-component-definition":
      [2, { "namedComponents": "arrow-function" }],
  }
